# Generated by Django 4.2.11 on 2024-03-07 13:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dentalAIApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='MedicalProduct',
        ),
    ]
