# Generated by Django 4.2.11 on 2024-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dentalAIApp', '0002_rename_product_medicalproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalproduct',
            name='price',
            field=models.IntegerField(default=100),
        ),
    ]
